#!/usr/bin/python3
# -*- coding:utf-8 -*-
"""
@author: Mollyviron
@file: index.py
@time: 2020/5/17 15:55
@desc:
"""
# Generated by Selenium IDE
from time import sleep

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

from PO.selenium_wework_add_member.page.contact import Contact


class Index(object):
    def __init__(self):
        options = Options()
        options.debugger_address = "127.0.0.1:9222"
        self._driver = webdriver.Chrome(options=options)
        self._driver.get('https://work.weixin.qq.com/wework_admin/frame#index')

    # def teardown_method(self):
    #     self._driver.quit()

    def goto_contact(self):
        self._driver.find_element(By.CSS_SELECTOR, '#menu_contacts>span').click()
        return Contact(self._driver)

