#!/usr/bin/python3
# -*- coding:utf-8 -*-
"""
@author: Mollyviron
@file: index.py
@time: 2020/5/17 15:55
@desc:
"""
# Generated by Selenium IDE
from time import sleep


from selenium.webdriver.common.by import By

from Selenium_PageObject.selenium_wework_add_member.page.contact import Contact


class Index():
    def goto_contact(self):
        self._driver.find_element(By.CSS_SELECTOR, '#menu_contacts>span').click()
        return Contact(self._driver)

